# Support tdesign-vue@naruto publish
name: naruto publish

on:
  push:
    branches: [naruto]

jobs:
  MERGED_INTO_NARUTO:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run build
      - name: publish
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.TDESIGN_NPM_TOKEN }}
          tag: ${{ 'naruto' }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
