name: Publish_Any_Commit
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    if: ${{ github.repository == 'Tencent/tdesign-vue' && !startsWith(github.head_ref, 'release/')}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: npm install

      - run: npm run build

      - run: node ./script/workflows/pkg-pr-new-generate-template.mjs

      - run: npx pkg-pr-new publish --compact  --template 'tdesign-vue2-demo/**'
