name: PREVIEW_SITE

on:
  pull_request:
    branches: [develop, main, release]

jobs:
  PREVIEW_SITE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
        shell: bash
      - run: echo '${{ github.ref }} ...  ${{ github.sha }}'
      - name: Build site
        run: npm run site:preview
      - name: Upload surge service and generate preview URL
        id: deploy
        run: |
          export GITHUB_SHA=${{ github.sha }}
          export GITHUB_SHA_SUB=${GITHUB_SHA: 0: 7 }
          export DEPLOY_DOMAIN=https://preview-$GITHUB_SHA_SUB-tdesign-vue.surge.sh
          npx surge --project ./_site --domain $DEPLOY_DOMAIN --token ${{ secrets.TDESIGN_SURGE_TOKEN }}
          echo the preview URL is $DEPLOY_DOMAIN
        if: ${{ success() }}
      - run: echo "🚀 This job's status is ${{ job.status }}."
